###
## configuration.yaml
###

homeassistant:
  allowlist_external_dirs:
    - '/config'

## DEFAULT

cloud:
config:
dhcp:
energy:
ffmpeg:
hassio:
image:
map:
media_source:
mobile_app:
my:
network:
person:
python_script:
scene:
script:
ssdp:
stream:
sun:
system_health:
tag:
timer:
usb:
webhook:
zeroconf:
zone:
homekit:

tts:
  - platform: google_translate

favicon:
  title: 'Age@Home'
  icon_path: /local/favicons/

sensor datetime:
  - platform: time_date
    display_options:
      - date
      - time

frontend:
  extra_module_url:
    - /local/resources/modules/history-explorer-card.js
    - /local/resources/modules/apexcharts-card.js
    - /local/resources/modules/card-mod.js
    - /local/resources/modules/mushroom.js
  themes: !include_dir_merge_named themes

###
## RECORDER, HISTORY, LOGBOOK components
###

logger: !include logger.yaml
recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml

###
## directory configuration
###

template: !include_dir_merge_list template/
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
automation: !include_dir_merge_list automation/
group: !include_dir_merge_named group/
counter: !include_dir_merge_named counter/
device_tracker: !include_dir_merge_list device_tracker/
shell_command: !include_dir_merge_named shell_command/
notify: !include_dir_merge_list notify/
input_select: !include_dir_merge_named input_select/
input_boolean: !include_dir_merge_named input_boolean/
input_text: !include_dir_merge_named input_text/
input_number: !include_dir_merge_named input_number/
panel_iframe: !include_dir_merge_named panel_iframe/
input_datetime: !include_dir_merge_named input_datetime/
utility_meter: !include_dir_merge_named utility_meter/

###
## mqtt is different
###

mqtt:
  sensor: !include_dir_merge_list mqtt/sensor
